name: Publish to DockerHub

on:
  push:
    tags:
      - "*"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@master

      - name: Download static files
        uses: i3h/download-release-asset@v1
        with:
          owner: ifconfig-is
          repo: web
          tag: latest
          file: static.tar.gz

      - name: Extract static files
        run: |
          mkdir static
          tar xzvf static.tar.gz --directory static
          pwd
          ls -lha

      - name: Compile
        run: |
          go build .

      - name: Build and push Docker images
        uses: docker/build-push-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          repository: ifconfigis/api
          tags: latest
